# Sets standard vars and generates VERSION_TAG for dev/staging
# Tag format:
#   - image tag format: "1.5.3"
#   - GitLab release format: "v1.5.3"
#   - app git tag format (feat/fix branch): "v1.5.3-c7754fc6"
#   - app git tag format (main branch): "v1.5.3"

.get_version:
  image: alpine/git:latest
  script:
    - |
      if [[ -z "$CI_COMMIT_TAG" ]]; then
        GIT_TAG="$CI_COMMIT_TAG"
        IMAGE_TAG="$(echo $GIT_TAG | sed 's/^v//')"

      else
        GIT_TAG="$(git describe --tags $(git rev-list --tags --max-count=1))-$CI_COMMIT_SHORT_SHA"
        IMAGE_TAG="$CI_COMMIT_SHORT_SHA"
      fi

      echo -e "\nGIT_TAG=$GIT_TAG\
        \nIMAGE_TAG=$IMAGE_TAG" \
        \
        > tags.env

      if [[ "$PIPELINE_DEBUG" == "true" ]]; then
        echo -e " \
          \n\e[31m##### tags.env contents: #####\e[0m \
          \n"
        cat tags.env
      fi
  artifacts:
    reports:
      dotenv: tags.env
