apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  environment: latest
# Prefix/Suffix required for VaultAuth configuration
#
namePrefix: infrastructure-documentation-
nameSuffix: -latest
# Facilitate kustomization name updating
#
configurations:
  - kustomizeconfig.yaml
commonAnnotations:
  version: 2.5.22-714103d0--2023-10-07.1696637349 # {"$imagepolicy": "infrastructure-documentation:infrastructure-documentation-image-policy-latest:tag"}
images:
  - name: "infrastructure-documentation"
    newName: "registry.ltc.bcit.ca/web-apps/infrastructure-documentation"
    newTag: "2.5.22-714103d0--2023-10-07.1696637349" # {"$imagepolicy": "infrastructure-documentation:infrastructure-documentation-image-policy-latest:tag"}
patches:
  # Patches ingress with "latest--"
  - target:
      kind: Ingress
    path: ingress-patch.yaml
  # Adds secrets to deployment
  - target:
      kind: Deployment
    path: deployment-patch.yaml
  # Incorporate vault-secrets
  #
  # adds `-latest` suffix to VaultAuth `spec.mount`
  - target:
      kind: VaultAuth
    path: vault-secrets-latest/vault-auth-patch.yaml
components:
  # Include environment-specific secrets
  - ./vault-secrets-latest
  # Required for VaultAuth role and serviceaccounts
  - ../../base/components/vault-auth
configMapGenerator:
  # Updates elasticapm config
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=infrastructure-documentation-latest
    behavior: merge
