apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infrastructure-documentation
resources:
  - ../../base
commonLabels:
  environment: latest
commonAnnotations:
  version: 2.5.10-f448fae7--2023-06-20.1687242953 # {"$imagepolicy": "infrastructure-documentation:infrastructure-documentation-image-policy:tag"}
images:
  - name: "infrastructure-documentation"
    newName: "registry.ltc.bcit.ca/web-apps/infrastructure-documentation"
    newTag: "2.5.10-f448fae7--2023-06-20.1687242953" # {"$imagepolicy": "infrastructure-documentation:infrastructure-documentation-image-policy:tag"}
patches:
  # Patches ingress to add "latest--" prefix to ingress URL
  #
  - target:
      kind: Ingress
    path: ingress-patch.yaml
    # Adds elasticapm config to deployment
    #
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value: [{"configMapRef": {"name":"elasticapm-config"}}]
# Generates elasticapm config
#
configMapGenerator:
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=infrastructure-documentation-latest
      - ELASTIC_APM_SERVER_URL=https://bcit-ltc.apm.westus2.azure.elastic-cloud.com
