apiVersion: v2
appVersion: 1.0.32
description: Information about the architecture and makeup of the LTC's server infrastructure.
icon: https://course-production.ltc.bcit.ca/favicon.ico
maintainers:
- email: ltc_techops@bcit.ca
  name: BCIT LTC
  url: https://www.bcit.ca/learning-teaching-centre/
name: infrastructure-documentation
sources:
- https://github.com/bcit-ltc/
version: 1.0.32
