# Default LTC GitLab CI/CD Pipeline

## General Steps
# 1. Gather info
# 2. Build Image
# 3. Generate deployment package
# 4. Deploy


## Include common scripts
include:
  - project: 'deployments/ci-config'
    file: 
      - '.build.yml'
      - '.build-new.yml'
      - '.deploy.yml'
      - '.semantic-tag.yml'
      - '.utilities.yml'


workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'


stages:
  - gather info
  - analyze for tagging
  - build
  - deploy
  - cleanup


## Determine git tag
get environment:
  stage: gather info
  extends: .get_version


## Build feat/fix branch image and push to project registry
build review image:
  stage: build
  extends:
    - .build_image
  tags:
    - $CLUSTER_NAME
  # rules:
  #   - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "release"'
  #     when: never
  #   - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_MERGE_REQUEST_EVENT_TYPE == "detached"'
  #     when: never
  #   - if: '$CI_PIPELINE_SOURCE == "push" && $CI_OPEN_MERGE_REQUESTS'


## Deploy feat/fix branch package
deploy review package:
  stage: deploy
  variables:
    BUILD_ENV: dev
    DEPLOY_NAMESPACE: $CI_COMMIT_REF_SLUG
    DEPLOY_HOST: $CI_PROJECT_NAME.$CLUSTER_NAME.reviews.dev.ltc.bcit.ca
  extends:
    - .deploy_review_package
    - .set_review_environment
  needs:
  - job: get environment
    artifacts: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_MERGE_REQUEST_EVENT_TYPE == "detached"'
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "release"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_OPEN_MERGE_REQUESTS'
      when: never



## Removes deployment (and all assets in the namespace)
stop_review:                          # Stop review environment
  stage: cleanup
  variables:
    BUILD_ENV: dev
    DEPLOY_NAMESPACE: $CI_COMMIT_REF_SLUG
  extends:
    - .undeploy_review_package



## Build main branch image and push to project registry
build latest image:
  stage: build
  extends:
    - .build_image
  tags:
    - staging
  rules:
    - if: '$CI_COMMIT_REF_SLUG == "main" && $CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "detached"'
      when: never

# Run Semantic Release
semver_tag:
  stage: analyze for tagging
  extends: 
    - .semantic_release
  secrets:
    GITLAB_TOKEN:
      vault: dependabot-$CI_PROJECT_NAME/token@tokens
      file: false
  script:
    - "semantic-release \
        --branches main \
        --repository-url $CI_PROJECT_URL \
        --plugins '@semantic-release/commit-analyzer, \
          @semantic-release/release-notes-generator, \
          @semantic-release/gitlab'"
  tags:
    - staging
  rules:
    - if: '$CI_COMMIT_REF_SLUG == "main" && $CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "detached"'
      when: never
  #   - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  #     when: never
  #   - if: '$CI_COMMIT_REF_SLUG == "main" && $CI_PIPELINE_SOURCE == "push"'

## Deploy latest image (staging)
# - trigger staging pipeline in deployments/{projectName}/staging
  # tags:
  #   - staging

## Deploy stable image (production)
# - trigger production pipeline that:
#   - unpacks trigger variables (CI_JOB_TOKEN, branch ref, image ref, target environment)
#     eg. --form token=${CI_JOB_TOKEN} --form ref=main --form "variables[IMAGE_REF]=${IMAGE_REF}" --form "variables[TARGET_ENVIRONMENT]=${TARGET_ENVIRONMENT}" "${CI_API_V4_URL}/projects/${MANIFEST_PROJECT_ID}/trigger/pipeline"'
#   - hydrates manifests
#   - commits to registry (at `/releases` path)
  # rules:
  #   - if: $CI_COMMIT_TAG
  # tags:
  #   - production


## Pipeline variables
variables:                  # other global variables are set in GitLab Admin: https://issues.ltc.bcit.ca/admin/application_settings/ci_cd
  CLUSTER_NAME: "dev-cp"    # options: dev-cp, dev-vsm
  DEPLOYMENT_PACKAGE_URL: https://gitlab-ci-token:$CI_JOB_TOKEN@$CI_SERVER_HOST/deployments/$CI_PROJECT_NAME.git/packages/$BUILD_ENV
  DEPLOYMENT_PACKAGE_VERSION: "v0.3"
  # PROD_NAMESPACE: "qcon"    # combine apps into one namespace if following microservice pattern; otherwise, set to ""
  VAULT_AUTH_ROLE: "dependabot-$CI_PROJECT_NAME"    # Standard policies: [default, jwt, read-tokens, read-apps, read-ssl-certificates]
  GIT_FETCH_EXTRA_FLAGS: "--tags"
  PIPELINE_DEBUG: "true"
  KUBE_CONTEXT: "ltc-infrastructure/gitlab-kubernetes-agent:gitlab-kubernetes-agent"
