# Default LTC GitLab CI/CD Pipeline
#
## Requirements
#   - run `project-init.sh` to generate GitLab Project Access Token and configure Vault
#   - `Dockerfile` in project root
#
## General Pipeline Steps
#   1. Gather info
#   2. Build Image
#   3. Hydrate deployment package
#   4. Deploy package
#

stages:
  - get tags
  - review
  - build
  - deploy
  - cleanup


## Determine if there are existing git tags or a new tag is required
get tags:
  stage: get tags
  extends:
    - .get_gitlab_token
    - .get_tags


## Build image and push to project registry
build image:
  trigger:
    include:
      - project: 'deployments/ci-config'
        ref: 'main'
        file: '.build.yml'


## Deploy feat/fix branch package
deploy review:
  stage: review
  variables:
    TARGET_ENV: dev
  extends:
    - .deploy_review
    - .deploy_review_environment
    - .deploy_review_rules


## Removes deployment (and all assets in the namespace)
stop review:
  stage: cleanup
  extends:
    - .undeploy_review
    - .undeploy_review_environment
    - .undeploy_review_rules


## Deploy latest image (staging)
# - trigger staging pipeline in deployments/{projectName}/staging
deploy to staging:
  stage: deploy
  variables:
    TARGET_ENV: staging
  extends:
    - .deploy
    - .deploy_staging_rules
  environment:
    name: staging
    url: https://$STAGING_HOST/$CI_PROJECT_NAME
  tags:
    - staging


## Deploy stable image (production)
# - trigger production pipeline in deployments/{projectName}/production
deploy to production:
  stage: deploy
  variables:
    TARGET_ENVIRONMENT: production
  extends:
    - .deploy
    - .deploy_prod_rules
  environment:
    name: production
    url: https://${PROD_HOST}/${CI_PROJECT_NAME}
  tags:
    - production

#
#
#
## ---------- Pipeline configuration ----------
#
#
#
variables:                    # other global variables are set in GitLab Admin: https://issues.ltc.bcit.ca/admin/application_settings/ci_cd
  CLUSTER_NAME: "dev-cp"      # options: dev-cp, dev-vsm
  # COMMON_NAMESPACE: "qcon"    # combine apps into one namespace if following microservice pattern; otherwise, set to ""
  GENERIC_DEPLOYMENT: ""  # options: true, anything else!
  #
  #   - if GENERIC_DEPLOYMENT="anything but true", the pipeline expects a deployment package to exist. Create a deployment package and
  #       configure the pipeline with the package version.
  #
  #   - see https://infrastructure-documentation.dev.ltc.bcit.ca/ for info.
  #
  DEPLOYMENT_PACKAGE_PROJECT_ID: 345
#
#
#
## ---------- It's generally bad to change anything below here ----------
#
#
#
## Other common pipeline variables
  VAULT_AUTH_ROLE: "dependabot-$CI_PROJECT_NAME"
  GIT_FETCH_EXTRA_FLAGS: "--tags"
  PIPELINE_DEBUG: "true"

## Include common scripts
include:
  - project: 'deployments/ci-config'
    file: 
      - '.build.yml'
      - '.deploy.yml'
      - '.get-tags.yml'
      - '.rules.yml'
      - '.utilities.yml'

## Specify which runner should pick up pipeline jobs
default:
  tags:
    - ${CLUSTER_NAME}

## Configure merge request pipelines
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH || $CI_COMMIT_TAG'