# Default LTC GitLab CI/CD Pipeline

## General Steps
# 1. Gather info
# 2. Build Image
# 3. Generate deployment package
# 4. Deploy


stages:
  - gather info
  - analyze for tagging
  - build
  - deploy
  - cleanup


## Determine git tag
get environment:
  stage: gather info
  extends: .get_version


## Build feat/fix branch image and push to project registry
build review image:
  stage: build
  extends:
    - .build_new
  tags:
    - $CLUSTER_NAME


## Deploy feat/fix branch package
deploy review package:
  stage: deploy
  variables:
    BUILD_ENV: dev
    DEPLOY_NAMESPACE: $CI_COMMIT_REF_SLUG
    DEPLOY_HOST: $CI_PROJECT_NAME.$CLUSTER_NAME.reviews.dev.ltc.bcit.ca
  extends:
    - .deploy_review_package
    - .set_review_environment
  needs:
  - job: get environment
    artifacts: true


## Build main branch image and push to project registry
build latest image:
  stage: build
  extends:
    - .build_new
  tags:
    - staging


## Run Semantic Release
semver_tag:
  stage: analyze for tagging
  extends: 
    - .semantic_release
  secrets:
    GITLAB_TOKEN:
      vault: dependabot-$CI_PROJECT_NAME/token@tokens
      file: false
  script:
    - "semantic-release \
        --branches main \
        --repository-url $CI_PROJECT_URL \
        --plugins '@semantic-release/commit-analyzer, \
          @semantic-release/release-notes-generator, \
          @semantic-release/gitlab'"
  tags:
    - staging


## Deploy latest image (staging)
# - trigger staging pipeline in deployments/{projectName}/staging
  # tags:
  #   - staging


## Deploy stable image (production)
# - trigger production pipeline
# - only run on new tag
  # rules:
  #   - if: $CI_COMMIT_TAG
  # tags:
  #   - production


## Removes deployment (and all assets in the namespace)
stop_review:                          # Stop review environment
  stage: cleanup
  variables:
    BUILD_ENV: dev
    DEPLOY_NAMESPACE: $CI_COMMIT_REF_SLUG
  extends:
    - .undeploy_review_package


## Include common scripts
include:
  - project: 'deployments/ci-config'
    file: 
      - '.build.yml'
      - '.deploy.yml'
      - '.semantic-tag.yml'
      - '.utilities.yml'


workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'


## Pipeline variables
variables:                  # other global variables are set in GitLab Admin: https://issues.ltc.bcit.ca/admin/application_settings/ci_cd
  CLUSTER_NAME: "dev-cp"    # options: dev-cp, dev-vsm
  DEPLOYMENT_PACKAGE_URL: https://gitlab-ci-token:$CI_JOB_TOKEN@$CI_SERVER_HOST/deployments/$CI_PROJECT_NAME.git/$BUILD_ENV
  DEPLOYMENT_PACKAGE_VERSION: "v0.6"
  # PROD_NAMESPACE: "qcon"    # combine apps into one namespace if following microservice pattern; otherwise, set to ""
  VAULT_AUTH_ROLE: "dependabot-$CI_PROJECT_NAME"    # Standard policies: [default, jwt, read-tokens, read-apps, read-ssl-certificates]
  GIT_FETCH_EXTRA_FLAGS: "--tags"
  PIPELINE_DEBUG: "true"
  KUBE_CONTEXT: "ltc-infrastructure/gitlab-kubernetes-agent:gitlab-kubernetes-agent"
