version: '3'

services:
  mkdocs:
    container_name: mkdocs
    image: polinux/mkdocs
    restart: always
    ports:
      - "8000:8000"
    environment:
      LIVE_RELOAD_SUPPORT: 'true'
      ADD_MODULES: 'fontawesome-markdown mkdocs-git-revision-date-localized-plugin mkdocs-material'
      FAST_MODE: 'true'
      DOCS_DIRECTORY: '/docs'
      GIT_REPO: 'git@issues.ltc.bcit.ca:ltc-infrastructure/documentation.git'
      UPDATE_INTERVAL: 15
      AUTO_UPDATE: 'true'
      GIT_BRANCH: 'main'
    volumes:
      - $HOME/.ssh/id_ed25519:/root/.ssh/id_ed25519
      - ./docs:/docs