site_name: LTC Infrastructure Documentation
site_url: https://infrastructure-documentation.ltc.bcit.ca/

repo_name: infrastructure-documentation
repo_url: https://issues.ltc.bcit.ca/ltc-infrastructure/infrastructure-documentation.git

theme:
  name: material
  custom_dir: overrides
  palette: 
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/brands/connectdevelop
    repo: fontawesome/brands/git-alt
  features:
    # - navigation.sections
    # - navigation.expand
    - navigation.indexes
    - navigation.tracking
    - navigation.top

plugins:
  - search

markdown_extensions:
  - abbr
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - toc:
      permalink: true

nav:
  - index.md
  - services-systems.md
  - For Developers:
    - 0_for-developers/index.md
    - 0_for-developers/getting-started.md
    - 0_for-developers/continuous-deployment.md
  - DevOps & Engineering:
    - 1_devops-engineering/index.md
    - Kubernetes:
      - 1_devops-engineering/kubernetes/index.md
      - 1_devops-engineering/kubernetes/role-cluster-details.md
    - CI/CD Pipelines:
      - 1_devops-engineering/ci-cd-pipelines/pipeline-overview.md
      - 1_devops-engineering/ci-cd-pipelines/deployment-packages.md
      - 1_devops-engineering/ci-cd-pipelines/pipeline-details.md
    - 1_devops-engineering/infrastructure-details.md
    - 1_devops-engineering/configuration-projects.md
    - 1_devops-engineering/infrastructure-dev.md
  - Tech Stack Documentation:
    - 2_tech-stack-documentation/index.md