site_name: LTC Infrastructure Documentation
site_url: https://infrastructure-documentation.ltc.bcit.ca/

repo_name: infrastructure-documentation
repo_url: https://issues.ltc.bcit.ca/ltc-infrastructure/infrastructure-documentation.git

theme:
  name: material
  custom_dir: overrides
  palette: 
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/brands/connectdevelop
    repo: fontawesome/brands/git-alt
  features:
    - navigation.sections
    - navigation.tracking
    - navigation.top

plugins:
  - search

markdown_extensions:
  - abbr
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - toc:
      permalink: true

nav:
  - index.md
  - services-systems.md
  - Development Workflow:
    - 0_dev-workflow/index.md
    - 0_dev-workflow/getting-started-dev.md
    - 0_dev-workflow/deployments-releases.md
  - CI/CD Pipelines:
    - 1_ci-cd-pipelines/pipeline-overview.md
    - 1_ci-cd-pipelines/deployment-packages.md
    - 1_ci-cd-pipelines/pipeline-details.md
  - Kubernetes:
    - 2_kubernetes/index.md
    - 2_kubernetes/role-cluster-details.md
  - Infrastructure:
    - 3_infrastructure/index.md
    - 3_infrastructure/infrastructure-details.md
    - 3_infrastructure/configuration-projects.md
    - 3_infrastructure/infrastructure-dev.md