site_name: LTC Infrastructure
site_url: https://stable.dev.ltc.bcit.ca/infrastructure-documentation/

repo_name: infrastructure-documentation
repo_url: https://issues.ltc.bcit.ca/ltc-infrastructure/infrastructure-documentation.git

# Set to false for local docs development
strict: false

theme:
  name: material
  palette: 
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/brands/connectdevelop
    repo: fontawesome/brands/git-alt
  features:
    - navigation.sections
    - navigation.tracking
    # - navigation.indexes
    - navigation.top

plugins:
  - search

markdown_extensions:
  - meta
  - abbr
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - toc:
      permalink: true

nav:
  - index.md
  - services-systems.md
  - Development Workflow:
    - dev-workflow/index.md
    - dev-workflow/getting-started-dev.md
    - dev-workflow/deployment-release.md
    - CI/CD Pipelines:
      - dev-workflow/pipeline-overview.md
      - dev-workflow/deployment-packages.md
      - dev-workflow/pipeline-details.md
  - Kubernetes:
    - kubernetes/index.md
    - kubernetes/role-cluster-details.md
  - Infrastructure:
    - infrastructure/index.md
    - infrastructure/infrastructure-details.md
    - infrastructure/configuration-projects.md
    - infrastructure/infrastructure-dev.md