site_name: LTC Infrastructure Documentation
site_url: https://infrastructure-documentation.ltc.bcit.ca/

repo_name: infrastructure-documentation
repo_url: https://issues.ltc.bcit.ca/web-apps/infrastructure-documentation.git

theme:
  name: material
  custom_dir: overrides
  palette: 
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/brands/connectdevelop
    repo: fontawesome/brands/git-alt
  features:
    # - navigation.sections
    # - navigation.expand
    - navigation.indexes
    - navigation.tracking
    # - navigation.top
    # - navigation.tabs

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      enabled: !ENV [CI, true]

markdown_extensions:
  - abbr
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home:
    - index.md
    - services-systems.md
  - For Developers:
    - 0_development-workflow/index.md
    - 0_development-workflow/getting-started.md
    - 0_development-workflow/development-workflow.md
    - 0_development-workflow/pipeline-initial-run.md
    - 0_development-workflow/continuous-deployment-overview.md
    - 0_development-workflow/developing-deployment-packages.md
    - 0_development-workflow/semantic-versioning.md
    - 0_development-workflow/secrets.md
    - 0_development-workflow/routes-endpoints.md
    - 0_development-workflow/continuous-deployment-details.md
  - Additional Details:
    - Container Development:
      - 1_workflow-details/index.md
      - 1_workflow-details/kubernetes.md
      - 1_workflow-details/deployments-releases.md
      - 1_workflow-details/pipeline-overview.md
      - 1_workflow-details/deployment-packages.md
    - Infrastructure:
      - 2_infrastructure-details/index.md
      - 2_infrastructure-details/node-details.md
      - 2_infrastructure-details/kubernetes-details.md
      - 2_infrastructure-details/pipeline-details.md
      - 2_infrastructure-details/configuration-projects.md
      - 2_infrastructure-details/developing-infrastructure.md
