apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: review
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: infrastructure-documentation
    app.kubernetes.io/version: 1.0.32
  name: infrastructure-documentation
---
apiVersion: v1
data:
  nginx.conf: |
    server {
        listen 8080 default_server;
        server_name _;
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }

        # redirect server error pages to the static page /50x.html
        #
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: review
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: infrastructure-documentation
    app.kubernetes.io/version: 1.0.32
  name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: review
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: infrastructure-documentation
    app.kubernetes.io/version: 1.0.32
  name: infrastructure-documentation-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: review
    app.kubernetes.io/name: infrastructure-documentation
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: review
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: infrastructure-documentation
    app.kubernetes.io/version: 1.0.32
  name: infrastructure-documentation-deployment
spec:
  progressDeadlineSeconds: 300
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: review
      app.kubernetes.io/name: infrastructure-documentation
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: review
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: infrastructure-documentation
        app.kubernetes.io/version: 1.0.32
    spec:
      containers:
        - env:
            - name: APP_NAME
              value: infrastructure-documentation
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: host.k3d.internal:5000/infrastructure-documentation:v1.0.32-12-g636e8b3-dirty
          imagePullPolicy: IfNotPresent
          name: infrastructure-documentation
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /etc/nginx/conf.d
              name: nginx-config
      serviceAccountName: infrastructure-documentation
      volumes:
        - emptyDir: {}
          name: tmp
        - configMap:
            name: nginx-config
          name: nginx-config
