---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deploy-vars
data:
  DEPLOY_NAMESPACE: 76-test
  GIT_TAG: stable
  IMAGE_TAG: stable
  INGRESS_SUBDOMAIN: review--76-test--infrastructure-documentation.ltc.bcit.ca
