apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentation
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: documentation
  replicas: 1
  template:
    metadata:
      labels:
        app: documentation
    spec:
      serviceAccountName: documentation
      containers:
        - name: documentation
          image: documentation