apiVersion: k3d.io/v1alpha2
kind: Simple
servers: 1
network: k3d
kubeAPI:
  hostIP: "0.0.0.0"
  hostPort: "6443"
# volumes:
#   - volume: /prometheus:/prometheus
#     nodeFilters:
#       - server[0]
ports:
  - port: 0.0.0.0:8080:80
    nodeFilters:
      - loadbalancer
  - port: 0.0.0.0:8443:443
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
  k3s:
    extraServerArgs:
      - --tls-san=127.0.0.1
      - --no-deploy=metrics-server
    extraAgentArgs: []
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime:
    labels:
      - label: foo=bar
        nodeFilters:
          - loadbalancer
env:
  - envVar: bar=baz
    nodeFilters:
      - all
