name: Pipeline CI Orchestrator

on:
  push:
    branches:
      - "*"

jobs:
  create-codespace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Create Codespace via REST API
        id: create_codespace
        run: |
          response=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/user/codespaces \
            -d "{\"repository\":\"${{ github.repository }}\",\"ref\":\"${{ github.ref_name }}\",\"devcontainer_path\":\".devcontainer\",\"display_name\":\"test-devcontainer\"}")
          echo "$response" > codespace_response.json
          codespace_id=$(jq -r '.id' codespace_response.json)
          echo "Created Codespace ID: $codespace_id"
          # write to GITHUB_OUTPUT instead of set-output
          echo "codespace_id=$codespace_id" >> $GITHUB_OUTPUT

      - name: Verify Codespace Status
        run: |
          codespace_id="${{ steps.create_codespace.outputs.codespace_id }}"
          status_response=$(curl -s -X GET \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/user/codespaces/$codespace_id)
          state=$(echo "$status_response" | jq -r '.state')
          echo "Codespace $codespace_id is in '$state' state"
      
# jobs:
#   pipeline-ci-orchestrator:
#     name: Execute Pipeline CI
#     uses: bcit-ltc/.github/.github/workflows/cp-pipeline-ci-reusable.yml@main
#     secrets:
#       HELM_REPO_PAT: ${{ secrets.HELM_REPO_PAT }}
#       DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}


# permissions:
#   contents: write # to be able to publish a GitHub release
#   issues: write # to be able to comment on released issues
#   pull-requests: write # to be able to comment on released pull requests
#   packages: write # Required for pushing images  

# jobs:
#   pipeline-manager:
#     name: Pipeline Manager
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#       # - name: Print all ENVS
#       #   run: printenv
#       - name: Run Dagger for pipeline-manager development testing
#         uses: dagger/dagger-for-github@8.0.0
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           HELM_REPO_PAT: ${{ secrets.HELM_REPO_PAT }}
#         with:
#           module: github.com/BCIT-LTC/daggerverse/pipeline-manager@35-add-prefix-for-latest-and-review
#           call: >-
#             run
#             --source=.
#             --github_token=env://GITHUB_TOKEN
#             --helm_repo_pat=env://HELM_REPO_PAT
#             --username=${{ github.actor }}
#             --app_name=${{ github.event.repository.name }}
#             --branch=${{ github.ref_name }}
#             --commit_hash=$(echo $GITHUB_SHA | cut -c1-7)
#             --registry_path=ghcr.io/${{ github.repository }}
#             --repository_url=${{ github.server_url }}/${{ github.repository }}
#           cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
#           version: "latest"
          
