name: Pipeline Manager

on:
  workflow_call:

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  packages: write # Required for pushing images  

jobs:
  pipeline-manager:
    name: Pipeline Manager
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Dagger for pipeline-manager
        uses: dagger/dagger-for-github@8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          module: github.com/BCIT-LTC/daggerverse/pipeline-manager
          call: >-
            run 
            --source=. 
            --github_token=env://GITHUB_TOKEN  
            --helm_repo_pat=${{ secrets.HELM_REPO_PAT }}
            --username=${{ github.actor }} 
            --branch=${{ github.ref_name }} 
            --commit_hash=$(echo $GITHUB_SHA | cut -c1-7) 
            --registry_path=ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]') 
            --repository_url=$(echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY)
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "latest"
          