name: Pipeline CI Orchestrator

on:
  push:
    branches:
      - "*"

jobs:
  pipeline-ci-orchestrator:
    name: Execute Pipeline CI
    uses: bcit-ltc/.github/.github/workflows/cp-pipeline-ci-reusable.yml@main

