name: Docker Image CI for GHCR

on:
  push:
    branches:
      - main
      - '[0-9]+-*'

permissions:
  contents: read # for checkout

jobs:

  determine-current-version:
    name: Determine Current Version
    runs-on: ubuntu-latest
    # outputs:
    #   version: ${{ steps.set-version.outputs.VERSION_NUM }}
    steps:
      - uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest tag
        id: get-latest-tag
        run: echo "LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_OUTPUT

      - name: Print latest tag
        run: echo "The latest tag is ${{ steps.get-latest-tag.outputs.LATEST_TAG }}"
  determine-next-version:
    name: Determine Next Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.VERSION_NUM }}
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - run: npm init -y
      - run: npm install --save-dev semantic-release @semantic-release/exec 
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: semantic release config
        run: |
          echo "Configuring local \".releaserc\" file..."
          echo '{
            "branches": [
              "main",
            ],
            "plugins": [
              "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              [
                "@semantic-release/exec",
                {
                  "verifyReleaseCmd": "echo ${nextRelease.version} > NEXT_VERSION"
                }
              ],
              "@semantic-release/github"
            ]
          }' \
            > .releaserc

          echo "  Done."
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GA_TOKEN }}
        run: npx semantic-release 
      - name: Set the version
        id: set-version
        run: |
          echo VERSION_NUM=$(cat NEXT_VERSION) >> $GITHUB_OUTPUT
      - name: verify the version
        run: |
          if [ -z "${{ steps.set-version.outputs.VERSION_NUM }}" ]; then
            echo "No version found, cancelling job."
            exit 0
          else
            echo "Version found: ${{ steps.set-version.outputs.VERSION_NUM }}"
          fi

          
  ## This is the step that determines the environment
  ## conditionally chooses latest, stable or review based on branch and commit
  determine-environment:
    name: Determine Environment
    needs: [determine-next-version]
    if: ${{ needs.determine-next-version.outputs.version != '' }}
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-environment.outputs.ENVIRONMENT }}
    steps:
      - uses: actions/checkout@v4
      - name: Set the environment
        id: set-environment
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            if [[ "$COMMIT_MESSAGE" =~ ^(fix\s*:\s*|feat\s*:\s*|major\s*:\s*) ]]; then
              ENV_NAME="stable"
            else
              ENV_NAME="latest"
            fi
          elif [[ "${{ github.ref_name }}" =~ ^[0-9]+-.*$ ]]; then
            ENV_NAME="review"
          fi
          
          echo ENVIRONMENT=$ENV_NAME >> $GITHUB_OUTPUT

      - name: print the environment
        run: echo "The environment is ${{ steps.set-environment.outputs.ENVIRONMENT }}"

  build-for-environment:
    name: Build
    needs: [determine-next-version, determine-environment]
    if: ${{ needs.determine-next-version.outputs.version != '' }}
    runs-on: ubuntu-latest
    environment: ${{ needs.determine-environment.outputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Print build environment
        run: echo "This is the ${{ needs.determine-environment.outputs.environment }} environment"
      - name: Print gathered version
        run: echo "The version is ${{ needs.determine-version.outputs.version }}"
      - name: Create Tag format based on environment
        run: |
          if [ "${{ needs.determine-environment.outputs.environment }}" == "latest" ]; then
            echo "latest" > TAG
          elif [ "${{ needs.determine-environment.outputs.environment }}" == "stable" ]; then
            echo "stable" > TAG
          else
            echo "review-${{ needs.determine-next-version.outputs.version }}" > TAG
          fi
      
      # create string with format {semverTag}-{date}--{gitShortSha}.{timeStamp}
      - name: Create Tag
        run: |
          echo "$(cat TAG)-$(date +'%Y%m%d')--$(git rev-parse --short HEAD).$(date +'%s')" > TAG


      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #       registry: ghcr.io
      #       username: ${{ github.actor }}
      #       password: ${{ secrets.GA_TOKEN }}
      # - name: Build and push the image
      #   run: |
      #       docker build . --tag ghcr.io/bcit-ltc/explore:$(cat NEXT_VERSION)
      #       docker push ghcr.io/bcit-ltc/explore:$(cat NEXT_VERSION)