name: Docker Image CI for GHCR

on:
  push:

permissions:
  contents: read # for checkout

jobs:
  gather-info:
    name: Gather info
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.VERSION_NUM }}
    steps:
      - uses: actions/checkout@v4
      - name: Set the version
        id: set-version
        run: echo "VERSION_NUM=1.1" >> $GITHUB_OUTPUT
      - name: print the version
        run: echo "The version is ${{ steps.set-version.outputs.version }}"

  latest-build:
    name: Build
    needs: [gather-info]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print
        run: echo "The next version is ${{ needs.gather-info.outputs.version }}"