apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: app
build:
  insecureRegistries:
    - registry.localhost
  artifacts:
    - image: app
      # hooks:
      #   before:
      #     - command: ["sh", "-c", "kd.sh"]
      #       os: [darwin, linux]
          # - command: ["cmd.exe", "/C", "hook.bat"]
          #   os: [windows]
      sync:
        infer:
        - 'docs/'
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: app
        # If you want to allow overriding via env var CHART_PATH, fall back to a default:
        chartPath: ../app-chart
        namespace: app
        createNamespace: true
        setValueTemplates:
          image.registry: "{{.IMAGE_DOMAIN_app}}"
          image.repository: "{{.IMAGE_REPO_NO_DOMAIN_app}}"
          image.tag: "{{.IMAGE_TAG_app}}"
