apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: app
build:
  insecureRegistries:
    - registry
  artifacts:
    - image: app
  local:
    useBuildkit: true
profiles:
  - name: quickcheck
    test:
      - image: app
        structureTests:
          - "./test/example/container-structure-test.yaml"
# verify:
#   - name: alpine-wget
#     container:
#       name: alpine-wget
#       image: alpine:3.15.4
#       command: ["/bin/sh"]
#       args: ["-c", "wget http://www.google.com"]
deploy:
  helm:
    releases:
      - name: app
        chartPath: app-chart
        namespace: app
        createNamespace: true
        setValueTemplates:
          image.registry: "{{.IMAGE_DOMAIN_app}}"
          image.repository: "{{.IMAGE_REPO_NO_DOMAIN_app}}"
          image.tag: "{{.IMAGE_TAG_app}}"
